### ISSUE TITLE
How do I build and run this?

### ISSUE THREAD

**Issue by casperbang** [oWCTejLVlFyNztcBnOoh/gr-wmbus#1]

**Comment by oWCTejLVlFyNztcBnOoh** [comment]
In a nutshell: Build or install gnuradio. The code is python/gnuradio-companion only, i.e. go to apps/ and run wmbus_rx.py or play around with the gnuradio-companion files in grc/.

**Comment by heimao0130** [comment]
hello！which gnuradio version should i use ?very expecting your reply.thank you ！

**Comment by mirakonta** [comment]
Hello heimao0123,

I recommend you the fork https://github.com/jmichelp/gr-wmbus
works with latest gnuradio version

**Comment by heimao0130** [comment]
hello! mirakonta.very thanks for your reple! i get the gr-wmbus at the link you give,and  i build ,install the gr-wmbus sucessfully.but when i use the .grc files,i get the error missing block？maybe my gnuradio version is late?  i use the 3.7.4. very appericate your instructions. i am busy in my subject on gnuradio.thanks!

**Comment by sledzik1984** [comment]
Anybody can help:

root@debian:~/gr-wmbus/gr-wmbus/apps# ./wmbus_rx.py
linux; GNU C++ version 4.9.1; Boost_105500; UHD_003.007.003-0-unknown

gr-osmosdr 0.1.3 (0.1.3) gnuradio 3.7.5
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy 
Using device #0 Realtek RTL2838UHIDIR SN: 00000013
Found Rafael Micro R820T tuner
Using Volk machine: sse4_2_64_orc
Traceback (most recent call last):
  File "./wmbus_rx.py", line 222, in <module>
    tb = wmbus_rx(options.file, options.capture, options.verbose, options.freq_error)
  File "./wmbus_rx.py", line 170, in **init**
    self.sink = wmbus_phy1(msgq=self.msgq, verbose=verbose, freq_error=freq_error);
  File "/usr/local/lib/python2.7/dist-packages/wmbus/wmbus_phy1.py", line 44, in **init**
    self.any_sink_0_1 = mbus.framer(msgq, verbose) 
  File "/usr/local/lib/python2.7/dist-packages/wmbus/wmbus_blocks.py", line 49, in **init**
    out_sig = None, #[numpy.uint8],
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/runtime_swig.py", line 2238, in **init**
    def **init**(self, _args, *_kwargs): raise AttributeError("No constructor defined")
AttributeError: No constructor defined
